// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
       return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAren1fKq3QVfdxIl9WYsMiP651Px_TViI',
    appId: '1:152393665335:android:136ea586b075c998f7a8b2',
    messagingSenderId: '152393665335',
    projectId: 'nashhouse-6656c',
    storageBucket: 'nashhouse-6656c.appspot.com',
    databaseURL: 'https://nashhouse-6656c.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj0g6nPjWxccb5ka2c-uRe0gyHqvFTd4Q',
    appId: '1:152393665335:ios:644b99a1cab7905ef7a8b2',
    messagingSenderId: '152393665335',
    projectId: 'nashhouse-6656c',
    storageBucket: 'nashhouse-6656c.appspot.com',
    iosBundleId: 'com.example.ituApp',
    databaseURL: 'https://nashhouse-6656c.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDRS6M8Su9t5asJyHmrpndzgV1LnkF41ik",
      authDomain: "nashhouse-6656c.firebaseapp.com",
      projectId: "nashhouse-6656c",
      storageBucket: "nashhouse-6656c.appspot.com",
      messagingSenderId: "152393665335",
      appId: "1:152393665335:web:987e8d51b3ab4e73f7a8b2",
      databaseURL: 'https://nashhouse-6656c.firebaseio.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
      apiKey: "AIzaSyDRS6M8Su9t5asJyHmrpndzgV1LnkF41ik",
      authDomain: "nashhouse-6656c.firebaseapp.com",
      projectId: "nashhouse-6656c",
      storageBucket: "nashhouse-6656c.appspot.com",
      messagingSenderId: "152393665335",
      appId: "1:152393665335:web:9f1b8c3b4fd2a3daf7a8b2",
      databaseURL: 'https://nashhouse-6656c.firebaseio.com',
  );

}
